required = [
    "github.com/emicklei/go-restful",
    "github.com/onsi/ginkgo", # for test framework
    "github.com/onsi/gomega", # for test matchers
    "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
    "k8s.io/code-generator/cmd/client-gen", # for go generate
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    "sigs.k8s.io/controller-runtime/pkg/client/config",
    "sigs.k8s.io/controller-runtime/pkg/controller",
    "sigs.k8s.io/controller-runtime/pkg/handler",
    "sigs.k8s.io/controller-runtime/pkg/manager",
    "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
    "sigs.k8s.io/controller-runtime/pkg/source",
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1",
    ]

[prune]
  go-tests = true

[[override]]
  name = "github.com/pharmer/pharmer"
  revision = "006bbae3741e75a6b446eaa7ff08b0bf0a1d8de6"
  source = "git@github.com:appscode-cloud/pharmer.git"

[[override]]
  name = "github.com/linode/linodego"
  version = "=v0.7.1"

[[override]]
  name = "github.com/packethost/packngo"
  branch = "master"

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "=v1.14.12"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "=v21.3.0"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "=v11.1.0"

[[override]]
  name = "github.com/graymeta/stow"
  source = "https://github.com/appscode/stow.git"
  branch =  "master"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.0"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "ac-1.13.0"
  source = "github.com/kmodules/apimachinery"

[[override]]
  name = "k8s.io/apiserver"
  branch = "ac-1.13.0"
  source = "github.com/kmodules/apiserver"

[[override]]
  name = "k8s.io/client-go"
  version = "=v10.0.0"

[[override]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.13.0"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.13.0"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "c59034cc13d587f5ef4e85ca0ade0c1866ae8e1d"

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "=v2.2.1"

[[override]]
  name = "sigs.k8s.io/yaml"
  version = "=v1.1.0"

# STANZAS BELOW ARE GENERATED AND MAY BE WRITTEN - DO NOT MODIFY BELOW THIS LINE.

[[constraint]]
  name="sigs.k8s.io/controller-runtime"
  version="v0.1.1"

[[constraint]]
  name="sigs.k8s.io/controller-tools"
  version="v0.1.1"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"
