apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: credentialformats.cloud.pharmer.io
spec:
  group: cloud.pharmer.io
  names:
    kind: CredentialFormat
    plural: credentialformats
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            displayFormat:
              type: string
            fields:
              items:
                properties:
                  envconfig:
                    type: string
                  form:
                    type: string
                  input:
                    type: string
                  json:
                    type: string
                  label:
                    type: string
                type: object
              type: array
            provider:
              type: string
          required:
          - provider
          - displayFormat
          - fields
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
