apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: cloudproviders.cloud.pharmer.io
spec:
  group: cloud.pharmer.io
  names:
    kind: CloudProvider
    plural: cloudproviders
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            credentials:
              items:
                properties:
                  apiVersion:
                    description: 'APIVersion defines the versioned schema of this
                      representation of an object. Servers should convert recognized
                      schemas to the latest internal value, and may reject unrecognized
                      values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
                    type: string
                  kind:
                    description: 'Kind is a string value representing the REST resource
                      this object represents. Servers may infer this from the endpoint
                      the client submits requests to. Cannot be updated. In CamelCase.
                      More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                    type: string
                  metadata:
                    type: object
                  spec:
                    properties:
                      annotations:
                        type: object
                      displayFormat:
                        type: string
                      fields:
                        items:
                          properties:
                            envconfig:
                              type: string
                            form:
                              type: string
                            input:
                              type: string
                            json:
                              type: string
                            label:
                              type: string
                          required:
                          - envconfig
                          - form
                          - json
                          - label
                          - input
                          type: object
                        type: array
                      provider:
                        type: string
                    required:
                    - provider
                    - displayFormat
                    - annotations
                    - fields
                    type: object
                type: object
              type: array
            kubernetes:
              items:
                properties:
                  apiVersion:
                    description: 'APIVersion defines the versioned schema of this
                      representation of an object. Servers should convert recognized
                      schemas to the latest internal value, and may reject unrecognized
                      values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
                    type: string
                  kind:
                    description: 'Kind is a string value representing the REST resource
                      this object represents. Servers may infer this from the endpoint
                      the client submits requests to. Cannot be updated. In CamelCase.
                      More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                    type: string
                  metadata:
                    type: object
                  spec:
                    properties:
                      envs:
                        type: object
                      version:
                        type: object
                    required:
                    - version
                    type: object
                type: object
              type: array
            machineTypes:
              items:
                properties:
                  apiVersion:
                    description: 'APIVersion defines the versioned schema of this
                      representation of an object. Servers should convert recognized
                      schemas to the latest internal value, and may reject unrecognized
                      values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
                    type: string
                  kind:
                    description: 'Kind is a string value representing the REST resource
                      this object represents. Servers may infer this from the endpoint
                      the client submits requests to. Cannot be updated. In CamelCase.
                      More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                    type: string
                  metadata:
                    type: object
                  spec:
                    properties:
                      category:
                        type: string
                      cpu:
                        type: object
                      deprecated:
                        type: boolean
                      description:
                        type: string
                      disk:
                        type: object
                      ram:
                        type: object
                      regions:
                        items:
                          type: string
                        type: array
                      sku:
                        type: string
                      zones:
                        items:
                          type: string
                        type: array
                    required:
                    - sku
                    - description
                    - cpu
                    - ram
                    type: object
                type: object
              type: array
            name:
              type: string
            regions:
              items:
                properties:
                  apiVersion:
                    description: 'APIVersion defines the versioned schema of this
                      representation of an object. Servers should convert recognized
                      schemas to the latest internal value, and may reject unrecognized
                      values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
                    type: string
                  kind:
                    description: 'Kind is a string value representing the REST resource
                      this object represents. Servers may infer this from the endpoint
                      the client submits requests to. Cannot be updated. In CamelCase.
                      More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                    type: string
                  metadata:
                    type: object
                  spec:
                    properties:
                      location:
                        type: string
                      region:
                        type: string
                      zones:
                        items:
                          type: string
                        type: array
                    required:
                    - location
                    - region
                    type: object
                type: object
              type: array
          required:
          - name
          - regions
          - machineTypes
          - credentials
          - kubernetes
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
